# Generated by Django 5.2.3 on 2025-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.CharField(default='C1', help_text='Буквенно-цифровой идентификатор блока (например, C1, C2)', max_length=10, verbose_name='Блок здания'),
        ),
    ]
