# Generated by Django 5.2.3 on 2025-06-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_course_course_year_course_is_mook_course_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='elective_group',
            field=models.CharField(blank=True, help_text='Identifier for grouping elective courses', max_length=32, null=True, verbose_name='Elective Group'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Is this course an elective?', verbose_name='Is Elective'),
        ),
        migrations.AddField(
            model_name='course',
            name='parent_course',
            field=models.ForeignKey(blank=True, help_text='Link to parent course for lecture/seminar/practice sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_courses', to='academics.course', verbose_name='Parent Course'),
        ),
    ]
