# Generated by Django 5.2.3 on 2025-06-25 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('import', 'Импорт'), ('export', 'Экспорт')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'В очереди'), ('STARTED', 'Выполняется'), ('SUCCESS', 'Завершено'), ('FAILURE', 'Ошибка')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_url', models.CharField(blank=True, max_length=255, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача импорта/экспорта расписания',
                'verbose_name_plural': 'История задач импорта/экспорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
